name: Find Changed files
description: Find files that have been modified during workflow execution.
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  files:
    description: Comma separated list of files to check for changes.
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.files }}
branding: 
  icon: search
  color: white
